### ISSUE TITLE
error "graphql_public" does not exists with cli supabase start

### ISSUE THREAD

**Issue by GaryAustin1** [supabase/postgres#169]
# Bug report

A customer using the CLI with a new install is getting this:

"I'm trying to execute. supabase start but i got this error  Error: Error starting database: ERROR:  schema "graphql_public" does not exist"

No info yet, but putting this out here in case the code added here for pg_graphql is already being installed by the CLI and there might be an issue with the pg_graphql extension.   Would not have expected customer to run into it yet.

@olirice I noticed the push 4 days ago, so flagging in case an early issue has been found.

**Comment by GaryAustin1** [comment]
@olirice I was reporting it as a user on discord hit it and I knew you were in the process of rolling it out but not announced yet... Figured something got "released" early.
I pointed them here, but they did not comment.  I'll see if I can find the post again, but I'm sure by now they got past it.

**Comment by simlevesque** [comment]
@GaryAustin1 I'm actually having this same issue. I can't start supabase after linking with the remote db.

**Comment by olirice** [comment]
@soedirgo ^

do you have any ideas how that could happen 23.10?

**Comment by soedirgo** [comment]
Probably not specific to 23.10, rather the same problem you mentioned re: supabase/postgres image being out of sync. Should be fixed with https://github.com/supabase/cli/pull/232, coming out in the next release.

**Comment by simlevesque** [comment]
I actually had this bug before 23.10 so that makes sense. I should have said that previously.

**Comment by simlevesque** [comment]
@olirice I'm afraid that the problem is still present.

```
~/w/supabase-test  main• ❱ supabase start
Error: supabase start is already running. Try running supabase stop first.
~/w/supabase-test  main• [1] supabase stop
Stopped local development setup.
~/w/supabase-test main• ❱ supabase start
⣻ Applying migration 20220401210615_remote_commit.sq
Error: Error starting database: ERROR:  schema "graphql_public" does not exist

⏎                                                                                                                                                                                                               ~/w/supabase-test  main• 46.1s [1] supabase -v
0.24.0
```

I even tried to reset all my local files, I still get the same issue. It pulled the new supabase/postgresql.

**Comment by olirice** [comment]
@simlevesque yes, please send your project ref and I'll take a look

**Comment by soedirgo** [comment]
I tried replicating this and don't get the `graphql_public.graphql` DDL above in `remote_commit.sql`.

One thing you can try to fix this is to empty `remote_commit.sql` and put `CREATE EXTENSION IF NOT EXISTS pg_graphql SCHEMA extensions;` in (undocumented) `supabase/extension.sql`. We're working on fixing Postgres permissions so that you can do `CREATE EXTENSION` in a migration, which you currently can, but wouldn't work when you push the migration.

**Comment by princemaple** [comment]
Same issue.

If I comment out the 2 `graphql_public` clauses, I still get this:
`function extensions.moddatetime() does not exist`

An issue with all the extensions?

My project was created mostly in the browser. I only just started using the cli now and did `remote commit` the first time.

**Comment by soedirgo** [comment]
Yes, an issue with all extensions unfortunately. In your case you might want to do `CREATE EXTENSION IF NOT EXISTS moddatetime SCHEMA extensions;` as well.

**Comment by princemaple** [comment]
Thanks for the confirmation and the workaround. It's a pretty amazing product nonetheless.

**Comment by simlevesque** [comment]
@olirice 

jwycethvnuypxtlvclfs

Sorry for the late reply.

**Comment by olirice** [comment]
@simlevesque did you see these steps https://github.com/supabase/postgres/issues/169#issuecomment-1088125830?

if that doesn't help, could you please try to create a minimal reproducible example that leads to your error so we can reproduce it locally to debug?

Something along the lines of:
- create a new supabase project
- in a new directory run `supabase init`
- next run ...
- then create a migration using .... containing `create table ...`
- finally run ... and get the error message ...

would be really helpful

**Comment by simlevesque** [comment]
@olirice that project ref I sent you is exactly that. It's a brand new project with absolutely nothing else in it. Do you want me to try again with a new/specific cli version ?

**Comment by madsbuch** [comment]
I am experiencing this on supabase CLI version 0.24.2 (as freshly setup yesterday).

**Comment by olirice** [comment]
@simlevesque @madsbuch 

Here are the steps I used to attempt to recreate the error you're seeing

1. Created a new supabase project
2. Retrieved the project_ref and db_connection_string
3. Set up a new repo locally for manage the project
```sh
mkdir myproj
cd myproj
git init
supabase init
supabase start
supabase link --project-ref <project_ref>
supabase db remote set '<db_connection_string>'
supabase db remote commit
```
4. Connected to the local database (# Default URL:
postgresql://postgres:postgres@localhost:54322/postgres) and created a new todo table
```sql
create table todo(
	id int primary key
);
```
5. Created a migration for the todo table
```sh
supabase db commit add_todo_table
```
6. Pushed the changes to supabase project <project_ref>
7. Confirmed <project_ref> contained my `todo` table

During that process I did not encounter any errors.

If your setup process differs from what I listed above, please provide an equivalent script that I can use for debugging.
It would also be helpful if you could follow the steps above exactly and lmk if it succeeded for you

thanks
